framework:
    messenger:
        # failure_transport: failed
 
        transports:
            async: 'sync://'
            async_priority_high: 'sync://'
 
        default_bus: messenger.bus.default
 
        buses:
            messenger.bus.default: []
 
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
 
            # Route your messages to the transports
            # 'App\Message\YourMessage': async