nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/product
            - filter-products
            - cart
            - admin
            - login
            - logout
            - register
    documentation:
        info:
            title: "Stubborn Shop"
            description: "API de la boutique Stubborn"
            version: "1.0.0"
        components:
            schemas:
                Product:
                    type: object
                    properties:
                        id:
                            type: integer
                            description: Identifiant unique du produit
                            example: 1
                        name:
                            type: string
                            description: Nom du produit
                            example: "T-shirt"
                        imageFile:
                            type: string
                            format: binary
                            description: Fichier image du produit
                        imageName:
                            type: string
                            description: Nom de l'image du produit
                            example: "tshirt.jpg"
                        price:
                            type: number
                            format: float
                            description: Prix du produit
                            example: 19.99
                        stock_xs:
                            type: integer
                            description: Stock taille XS
                            example: 10
                        stock_s:
                            type: integer
                            description: Stock taille S
                            example: 15
                        stock_m:
                            type: integer
                            description: Stock taille M
                            example: 20
                        stock_l:
                            type: integer
                            description: Stock taille L
                            example: 25
                        stock_xl:
                            type: integer
                            description: Stock taille XL
                            example: 30
                        homepage:
                            type: boolean
                            description: Affiché sur la page d'accueil
                            example: true
                        updatedAt:
                            type: string
                            format: date-time
                            description: Date de la dernière mise à jour
                            example: "2023-06-01T12:00:00Z"
                User:
                    type: object
                    properties:
                        id:
                            type: integer
                            description: Identifiant unique de l'utilisateur
                            example: 1
                        username:
                            type: string
                            description: Nom d'utilisateur
                            example: "john_doe"
                        roles:
                            type: array
                            items:
                                type: string
                            description: Les rôles de l'utilisateur
                            example: ["ROLE_USER", "ROLE_ADMIN"]
                        email:
                            type: string
                            format: email
                            description: Adresse email de l'utilisateur
                            example: "john.doe@example.com"
                        password:
                            type: string
                            description: Mot de passe hashé de l'utilisateur
                            example: "$2y$13$..."
                        delivery_address:
                            type: string
                            description: Adresse de livraison de l'utilisateur
                            example: "123 Main St, Anytown, USA"
                        isVerified:
                            type: boolean
                            description: Statut de vérification de l'utilisateur
                            example: true
    
